services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: etl_pipeline_airflow

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: "SequentialExecutor"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/project
      - ./logs:/opt/airflow/logs

    ports:
      - "8080:8080"

    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
        --username airflow
        --password airflow
        --firstname Air
        --lastname Flow
        --role Admin
        --email airflow@example.com || true &&
      airflow scheduler &
      airflow webserver --host 0.0.0.0 --port 8080
      "